BY.RazorWebApp/Pages/Booking.cshtml.cs
using BY.Business;
using BY.Data.Models;
using BY.RazorWebApp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyApp.Namespace
{
    public class BookingModel : PageModel
    {
        private readonly ICourtBusiness _courtBusiness;

        [BindProperty]
        public string Search { get; set; } = "";
        [BindProperty]
        public string SortBy { get; set; } = "";
        [BindProperty]
        public string OrderBy { get; set; } = "";

        public List<Court> Courts { get; set; } = new List<Court>();
        public int TotalCount { get; set; } = 0;
        public int PageTotal { get; set; } = 0;
        public int CurrentPage { get; set; } = 0;
        public int PageSize { get; set; } = 0;
        public BookingModel()
        {
            _courtBusiness = new CourtBusiness();
        }

        public async Task<IActionResult> OnGetAsync()
        {
            string search = Request.Query["search"];
            string sortby = Request.Query["sortby"];
            string orderby = Request.Query["orderby"];

            Search = search ?? string.Empty;
            SortBy = sortby ?? string.Empty;
            OrderBy = orderby ?? string.Empty;
            if (!int.TryParse(Request.Query["page"], out int page))
            {
                page = 1;
            }
            if (!int.TryParse(Request.Query["pagesize"], out int pagesize))
            {
                pagesize = 8;
            }
            var result = await _courtBusiness.GetAllCourt();
            if (result != null && result.Status > 0)
            {
                if (result.Data != null)
                {
                    var query = result.Data as IEnumerable<Court>;
                    if (query != null && query.Any())
                    {
                        if (!string.IsNullOrWhiteSpace(search))
                        {
                            search = search.Trim().ToLower();
                            query = query.Where(x => x.Name.ToLower().Contains(search) || x.Address != null && x.Address.ToLower().Contains(search));
                        }
                        var PageCount = query.Count();
                        // Determine sorting
                        if (!string.IsNullOrWhiteSpace(sortby))
                        {
                            sortby = sortby.Trim().ToLower();
                            orderby = orderby?.Trim().ToLower() ?? "asc";

                            bool isAscending = orderby.Equals("asc");

                            query = sortby switch
                            {
                                "name" => isAscending ? query.OrderBy(x => x.Name) : query.OrderByDescending(x => x.Name),
                                "address" => isAscending ? query.OrderBy(x => x.Address) : query.OrderByDescending(x => x.Address),
                                _ => query
                            };
                        }

                        var pagedCourts = query
                            .Skip((page - 1) * pagesize)
                            .Take(pagesize)
                            .ToList();

                        Courts = pagedCourts;

                        TotalCount = PageCount;
                        PageTotal = (int)Math.Ceiling(PageCount / (double)pagesize);
                        CurrentPage = page;
                        PageSize = pagesize;
                    }
                }
            }
            return Page();
        }
    }
}

BY.RazorWebApp/Pages/CourtDetail.cshtml.cs
using BY.Business;
using BY.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Xml.Schema;

namespace MyApp.Namespace
{
    [IgnoreAntiforgeryToken]
    public class CourtDetailModel : PageModel
    {
        private readonly ICourtBusiness _courtBusiness;
        private readonly IScheduleBusiness _scheduleBusiness;

        public CourtDetailModel()
        {
            _courtBusiness ??= new CourtBusiness();
            _scheduleBusiness ??= new ScheduleBusiness();
        }
        [BindProperty]
        public Court Court { get; set; } = default!;

        public string? Error { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int id)
        {
            var court = await _courtBusiness.GetById(id);
            if (court != null && court.Status > 0)
            {
                if (court.Data != null)
                {
                    Court = court.Data as Court;

                }
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAddBooking()
        {
            string sessionCart = HttpContext.Session.GetString("cart");
            List<Cart>? carts = new List<Cart>();
            if (!string.IsNullOrEmpty(sessionCart))
            {
                carts = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));
            }
            if (!int.TryParse(Request.Form["courtId"], out int courtId))
            {
                Error = "Not found court Id";
                await OnGetAsync(Court.CourtId);
                return Page();
            }
            var courtResult = await _courtBusiness.GetById(courtId);
            if (courtResult == null || courtResult.Status <= 0 || courtResult.Data == null)
            {
                Error = "Not found court";
                await OnGetAsync(Court.CourtId);
                return Page();
            }
            var court = courtResult.Data as Court;
            if (court == null)
            {
                Error = "Not found court";
                await OnGetAsync(Court.CourtId);
                return Page();
            }
            if (!DateOnly.TryParse(Request.Form["datePlay"], out DateOnly datePlay))
            {
                Error = "Date play invalid";
                await OnGetAsync(Court.CourtId);
                return Page();
            }

            if (!TimeOnly.TryParse(Request.Form["time"], out TimeOnly timePlay))
            {
                Error = "time play invalid";
                await OnGetAsync(Court.CourtId);
                return Page();
            }
            var cart = new Cart()
            {
                CourtId = court.CourtId,
                CourtName = court.Name,
                Image = court.Image,
                DatePlay = datePlay,
                TimePlay = timePlay,
            };

            if (cart != null)
            {
                if (CheckExist(carts, court, datePlay, timePlay))
                {
                    Error = $"Date play: {datePlay.ToString("dd-MM-yyyy")} , Time play: {timePlay}, Court: {court.Name} already included in booking";
                    await OnGetAsync(Court.CourtId);
                    return Page();
                }
                carts.Add(cart);
            }
            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(carts));
            return RedirectToPage("./Payment");
        }
        public async Task<IActionResult> OnPostGetTimeAsync(int courtId, DateOnly datePlay)
        {
            Dictionary<string, TimeOnly> timeValue = new Dictionary<string, TimeOnly>{
                { "05:00", new TimeOnly(5,00) },
                { "06:00", new TimeOnly(6,00) },
                { "07:00", new TimeOnly(7,00) },
                { "08:00", new TimeOnly(8,00) },
                { "09:00", new TimeOnly(9,00) },
                { "15:00", new TimeOnly(15,00) },
                { "16:00", new TimeOnly(16,00) },
                { "17:00", new TimeOnly(17,00) },
                { "18:00", new TimeOnly(18,00) },
                { "19:00", new TimeOnly(19,00) },
                { "20:00", new TimeOnly(20,00) },
                { "21:00", new TimeOnly(21,00) },
            };
            if(datePlay == DateOnly.FromDateTime(DateTime.Now)){
                foreach(var time in timeValue.Keys){
                    if(timeValue[time].Hour <= TimeOnly.FromDateTime(DateTime.Now).Hour){
                        timeValue.Remove(time);
                    }
                }
            }
            var jsonOptions = new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.Preserve
            };
            var result = await _scheduleBusiness.GetTimeCanPlay(courtId, datePlay);
            string html = "";

            if (result != null && result.Status > 0 && result.Data != null)
            {
                var timeBooked = result.Data as List<string>;
                if (timeBooked != null)
                {
                    foreach (string time in timeBooked)
                    {
                        if (timeValue.ContainsKey(time))
                        {
                            timeValue.Remove(time);
                        }
                    }
                }
            }
            foreach (var key in timeValue.Keys)
            {
                html += $"<option value='{timeValue[key]}'>{key}</option>";
            }
            var jsonResult = System.Text.Json.JsonSerializer.Serialize(html, jsonOptions);
            return Content(jsonResult, "application/json");
        }

        private bool CheckExist(List<Cart> carts, Court court, DateOnly datePlay, TimeOnly timePlay)
        {
            foreach (var item in carts)
            {
                if (item.CourtId == court.CourtId
                    && item.DatePlay == datePlay
                    && item.TimePlay == timePlay)
                {
                    return true;
                }
            }
            return false;
        }
    }
}

BY.RazorWebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace BY.RazorWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

BY.RazorWebApp/Pages/Index.cshtml.cs
using BY.Business;
using BY.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BY.RazorWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ICourtBusiness _courtBusiness;

        [BindProperty]
        public List<Court>? Courts { get; set; } = new List<Court>();
        public IndexModel()
        {
            _courtBusiness = new CourtBusiness();
        }

        public async Task<IActionResult> OnGetAsync()
        {
            var courts = await _courtBusiness.GetTop8Court();
            if (courts.Status > 0 && courts.Data != null)
            {
                Courts = courts.Data as List<Court>;
            }
            return Page();
        }
    }
}

BY.RazorWebApp/Pages/Login.cshtml.cs
using BY.Business;
using BY.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace MyApp.Namespace
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public string Error { get; set; } = string.Empty;
        private readonly IAccountBusiness _accountBusiness;
        [BindProperty]
        public string Username { get; set; }
        [BindProperty]
        public string Password { get; set; }
        public LoginModel()
        {
            _accountBusiness = new AccountBusiness();
        }
        public async Task<IActionResult> OnPost()
        {
            var result = await _accountBusiness.Login(Username, Password);
            if(result.Status > 0)
            {
                var customer = result.Data as Customer;
                HttpContext.Session.SetString("customer", JsonConvert.SerializeObject(customer));
               return RedirectToPage("/Index");
            }
            else
            {
                Error = "Username or password invalid";
            }
            return Page();
        }
    }
}

BY.RazorWebApp/Pages/Logout.cshtml.cs
using BY.Business;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace BY.RazorWebApp.Pages
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.Session.SetString("customer", "");
            return RedirectToPage("/Index");
        }
    }
}

BY.RazorWebApp/Pages/Payment.cshtml.cs
using BY.Business;
using BY.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace MyApp.Namespace
{
    public class PaymentModel : PageModel
    {
        private readonly IBookingBusiness _bookingBusiness;
        private readonly IScheduleBusiness _scheduleBusiness;
        public PaymentModel()
        {
            _bookingBusiness = new BookingBusiness();
            _scheduleBusiness = new ScheduleBusiness();
        }
        [BindProperty]
        public string? Error { get; set; }
        [BindProperty]
        public bool Success { get; set; } = false;
        [BindProperty]
        public List<Cart> Carts { get; set; } = default!;

        public Customer Customer { get; set; } = new Customer();
        public void OnGet()
        {
            Success = false;
            string sessionCart = HttpContext.Session.GetString("cart");
            List<Cart>? carts = new List<Cart>();
            if (!string.IsNullOrEmpty(sessionCart))
            {
                carts = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));
            }
            Carts = carts;

            var customerJson = HttpContext.Session.GetString("customer");
            if (!string.IsNullOrEmpty(customerJson))
            {
                var customer = JsonConvert.DeserializeObject<Customer>(customerJson);
                Customer = customer;
            }
        }
        public async Task<IActionResult> OnPost()
        {
            OnGet();
            Customer.Name = Request.Form["name"];
            Customer.Email = Request.Form["email"];
            Customer.Address = Request.Form["address"];
            Customer.Phone = Request.Form["phone"];
            var result = await _bookingBusiness.CreateBookingV2(Carts, Customer);
            if (result.Status > 0)
            {
                Success = true;
                HttpContext.Session.SetString("cart", "");
            }
            else
            {
                Error = result.Message;
            }
            return Page();
        }

        public IActionResult OnPostDeleteCart(string cartId)
        {
            if (int.TryParse(cartId, out int index))
            {
                string sessionCart = HttpContext.Session.GetString("cart");
                List<Cart>? carts = new List<Cart>();
                if (!string.IsNullOrEmpty(sessionCart))
                {
                    carts = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));
                    for (int i = 0; i < carts.Count(); i++)
                    {
                        if (i == index)
                        {
                            carts.Remove(carts[i]);
                            break;
                        }
                    }
                    HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(carts));
                }
            }
            return RedirectToPage("/Payment");
        }
    }
}

BY.RazorWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BY.RazorWebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

BY.RazorWebApp/Pages/CourtDetail.cshtml
@page
@model MyApp.Namespace.CourtDetailModel
@{
    ViewData["Title"] = "Court detail";
}
@Html.AntiForgeryToken()
<div class="container-fluid py-5">
    <div class="shadow-lg rounded-3 shadow-lg py-3">
        <div class="row p-5">
            <div class="col-sm-12 col-lg-6 mb-4">
                <img class="w-100 h-100" src="@Model.Court.Image" alt="@Model.Court.Name" />
            </div>
            <div class="col-sm-12 col-lg-6">
                <form asp-page-handler="AddBooking" method="post" class="d-flex flex-column gap-3 px-5">
                    <input type="hidden" name="courtId" value="@(Model.Court.CourtId)" />
                    <h3 class="text-center">@Model.Court.Name</h3>
                    @if (string.IsNullOrEmpty(Model.Error) == false)
                    {
                        <div class="alert alert-danger">
                            @Model.Error
                        </div>
                    }
                    <h5 class="mt-3">Description:</h5>
                    <p>@Model.Court.Description</p>
                    <div class="d-flex align-items-center">
                        <h5 class="mb-0">Price: </h5>
                        <span class="mx-2">60k / h</span>
                    </div>
                    <div class="d-flex align-items-center">
                        <h5 class="mb-0">Date play: </h5>
                        <div class="form-group mx-2">
                            <label class="control-label sr-only">Date play</label>
                            <input name="datePlay" min="@DateTime.Now.Date.ToString("yyyy-MM-dd")" type="date"
                                   class="form-control" />
                        </div>
                    </div>
                    <div class="d-flex align-items-center">
                        <h5 class="mb-0">Start hour: </h5>
                        <div class="form-group mx-2 w-25">
                            <label class="control-label sr-only">Start hour</label>
                            <select id="timeSelect" name="time" class="form-control w-100">
                                <option value="">Chose hour</option>
                            </select>
                        </div>
                    </div>
                    <div class="mx-auto mt-4 w-75">
                        <button type="submit" class="btn btn-primary w-100">Booking</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

@section scripts {
    <script>
        $('input[name="datePlay"]').on('change', function () {
            let courtId = $('input[name="courtId"]').val();
            let datePlay = $(this).val();
            if (courtId && datePlay) {
                $.ajax({
                    type: "POST",
                    url: "/CourtDetail?handler=GetTime",
                    data: {
                        CourtId: courtId,
                        DatePlay: datePlay,
                    },
                    success: function (response) {
                        $('#timeSelect').html(response);
                    },
                    failure: function (response) {
                        alert("errorf");
                    },
                    error: function (response) {
                        alert("error");
                    }
                });
            } else {
                console.log("Court ID or datePlay is missing.");
            }
        });
    </script>
}

BY.RazorWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}

<div class="container-fluid py-5">
    <div class="position-relative mb-5">
        <img src="~/image/banner.png" class="h-50 w-100" style="object-fit: cover" />
        <div class="position-absolute" style="right: 8%; top: 40%">
            <h4>
                Sport for All with Booking Yard<br>
                Your One-Touch<br>
                Booking System<br>
            </h4>
            <a href="/Booking">
                <button type="button" class="mt-2 p-3 btn btn-dark rounded-pill">
                    Booking here <i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i>
                </button>
            </a>
        </div>
    </div>
    <div class="mt-5" style="background-color: #e6e6e6;">
        <h4 class="text-center pt-4">Yar For you</h4>
        <div class="p-4 row">
            @if (Model.Courts != null && Model.Courts.Count > 0)
            {
                foreach (var court in Model.Courts)
                {
                    <div class="col-lg-3 col-md-6 col-sm-12 mb-3">
                        <div class="card p-2" style="border-radius: 20px; width: 100%;">
                            <a asp-page="./CourtDetail" asp-route-id="@court.CourtId" style="height: 200px;">
                                <img src="@court.Image" class="card-img-top h-100" style="cursor: pointer;" alt="yard">
                            </a>
                            <div class="card-body">
                                <h5 class="card-title">@court.Name</h5>
                                <p class="card-text">
                                    <i class="fa fa-map-marker" aria-hidden="true">
                                        @court.Address</i>
                                </p>
                                <div class="float-end">
                                    <h5 class="my-auto">60k/h</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>

    </div>

    <div class="mt-5 mb-2">
        <h4 class="text-center pt-4">Acctractive features</h4>
        <h5 class="text-center text-muted">Features make it easier for you to book a yard on the website</h5>
        <div class="p-4 row justify-content-between">
            <div class="mx-2 my-2" style="width: 18rem">
                <img src="~/image/feature1.png" class="card-img-top mt-2" alt="yard">
                <div class="card-body">
                    <h5 class="text-center">Size and amentities</h5>
                    <p class="text-center">
                        Your badminton court can be designed according to standard dimensions, ensuring the space is
                        large enough for the match.
                    </p>
                </div>
            </div>
            <div class="mx-2 my-2" style="width: 18rem">
                <img src="~/image/feature2.png" class="card-img-top mt-2" alt="yard">
                <div class="card-body">
                    <h5 class="text-center">Playing floor and lighting</h5>
                    <p class="text-center">
                        Good lighting will create favorable conditions for the match to take place at all times, even in
                        the evening.
                    </p>
                </div>
            </div>
            <div class="mx-2 my-2" style="width: 18rem">
                <img src="~/image/feature3.png" style="height: 11rem;" class="card-img-top mt-2" alt="yard">
                <div class="card-body">
                    <h5 class="text-center">Online yard booking system</h5>
                    <p class="text-center">
                        The online course booking feature helps players easily plan.
                    </p>
                </div>
            </div>
        </div>
        <div class="p-4 row justify-content-around">
            <div class="mx-2 my-2" style="width: 21rem">
                <img src="~/image/feature4.png" class="card-img-top mt-2" alt="yard">
                <div class="card-body">
                    <h5 class="text-center">Reasonable and flexible prices</h5>
                    <p class="text-center">
                        Reasonable price policy suitable for students, workers with flexible hours, or groups who play
                        badminton regularly.
                    </p>
                </div>
            </div>
            <div class="mx-2 my-2" style="width: 21rem">
                <img src="~/image/feature5.png" style="height: 15.4rem;" class="card-img-top mt-2" alt="yard">
                <div class="card-body">
                    <h5 class="text-center">Customer care</h5>
                    <p class="text-center">
                        Dedicated customer care from assisting with field reservations to solving problems that arise
                        during play.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

BY.RazorWebApp/Pages/Logout.cshtml
@page
@model BY.RazorWebApp.Pages.LogoutModel
@{
}

BY.RazorWebApp/Pages/Payment.cshtml
@page
@model MyApp.Namespace.PaymentModel
@{
    ViewData["Title"] = "Payment";
}
@if (string.IsNullOrEmpty(Model.Error) == false)
{
    <div class="alert alert-danger">
        @Model.Error
    </div>
}
<div class="container my-5">
    @if (@Model.Success && Model.Carts != null)
    {
        <div class="row min-vh-100">
            <div class="d-flex justify-content-center" style="align-items: center;">
                <div class="text-center">
                    <img style="height: 200px; width: 200px;" src="~/image/success.webp" />
                    <h1 class="mb-4">Success !</h1>
                    <p>Your operation was completed successfully.</p>
                    <a href="/">
                        <button class="btn btn-dark rounded-3">Back to home</button>
                    </a>
                </div>
            </div>
        </div>
    }
    else
    {
        @if (Model.Carts != null && Model.Carts.Count > 0)
        {
            <div class="row shadow-lg py-5 rounded-3">
                <div class="col-lg-7 mb-4">
                    <h4 class="text-center mb-5">Booking</h4>
                    @{
                        for(int i =0; i < Model.Carts.Count; i++)
                        {
                            <div class="shadow-lg border-5 p-4 mt-3 position-relative"
                                 style="transition: transform 0.3s, box-shadow 0.3s;">
                                <div class="d-flex justify-content-between" style="align-items: center;">
                                    <img src="@Model.Carts[i].Image" alt="Court Image" style="height: 200px; width: 220px;" class="me-4">
                                    <div class="court-info flex-grow-1">
                                        <h3>@Model.Carts[i].CourtName</h3>
                                        <p>Start Date: <strong>@(Model.Carts[i].DatePlay.ToString("dd-MM-yyyy"))</strong></p>
                                        <p>Start Hour: <strong>@Model.Carts[i].TimePlay</strong></p>
                                        <p>Finish Hour: <strong>@Model.Carts[i].TimePlay.AddHours(1)</strong></p>
                                        <p>Price: <strong>60k / h</strong></p>
                                    </div>
                                    <div class="text-center">
                                        <p>Total Price</p>
                                        <span><strong>60k</strong></span>
                                    </div>
                                </div>
                                <span class="position-absolute top-0 p-2" style="right: 0; cursor: pointer;">
                                    <form method="post" asp-page-handler="DeleteCart">
                                        <input type="hidden" name="cartId" value="@i" />
                                        <button style="border: hidden" >
                                            <i class="fa fa-times" aria-hidden="true"></i>
                                        </button>
                                    </form>
                                </span>
                            </div>
                        }
                    }
                    <div class="mt-3 d-flex justify-content-center">
                        <a href="/Booking" class="w-100 text-center">
                            <button class="btn btn-primary booking-button">Booking more</button>
                        </a>
                    </div>
                </div>
                <div class="col-lg-5">
                    <h4 class="text-center">Customer</h4>
                    <form method="post" class="mt-5">
                        <div class="row">
                            <div class="col-6 form-group">
                                <label asp-for="@Model.Customer!.Name" class="mb-1" for="inputName">Name</label>
                                <input asp-for="@Model.Customer!.Name" id="inputName" type="text" class="form-control" name="name">
                            </div>
                            <div class="col-6 form-group">
                                <label asp-for="@Model.Customer!.Email" class="mb-1" for="inputEmail">Email</label>
                                <input asp-for="@Model.Customer!.Email" id="inputEmail" name="email" type="email"  class="form-control">
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-6 form-group">
                                <label asp-for="@Model.Customer!.Address" class="mb-1" for="inputAddress">Address</label>
                                <input asp-for="@Model.Customer!.Address" id="inputAddress" type="text" class="form-control"  name="address">
                            </div>
                            <div class="col-6 form-group">
                                <label asp-for="@Model.Customer!.Phone" class="mb-1" for="inputPhone">Phone</label>
                                <input asp-for="@Model.Customer!.Phone" id="inputPhone" type="text" name="phone" class="form-control">
                            </div>
                            <button type="submit" class="btn btn-primary mt-5 w-50 mx-auto">Payment</button>
                        </div>
                    </form>
                </div>
            </div>
        }
        else
        {
            <div class="row min-vh-100">
                <div class="d-flex justify-content-center" style="align-items: center;">
                    <div class="text-center">
                        <img style="height: 200px; width: 200px;" src="~/image/empty.png" />
                        <h1 class="mb-4">Empty booking</h1>
                        <p>You haven't booked any courses yet.</p>
                        <a href="/Booking">
                            <button class="btn btn-dark rounded-3">Back to booking</button>
                        </a>
                    </div>
                </div>
            </div>
        }
    }
</div>